            - name: googifloop.nekoweb
  # You may pin to the exact commit or the version.
  # uses: indiefellas/deploy2nekoweb@143fee495be60339b53595023bab68794ca535fa
  uses: indiefellas/deploy2nekoweb@v1.0.1
  with:
    # Your nekoweb API key.
    nekoweb-api-key: 9e068b5aa36a30070d3b76392862468b327323abca88971ebd0f2957623c872a
    # The nekoweb domain to deploy to.
    nekoweb-domain: googifloop.nekoweb.org
    # Your Nekoweb username. (Required for Recently Updated feature)
    nekoweb-username: googifloop
    # The directory you would like to deploy.
    directory: googifloop.nekoweb.org
          
