name: Update Version File
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: write ver to version.txt
        run: |
          echo "commit <a href='https://github.com/googifloop/googifloop.github.io/commit/$(git rev-parse --short HEAD)'>$(git rev-parse --short HEAD)</a> ($(date +'%m/%d/%Y'))" > version.txt

      - name: make extra commit for version.txt
        run: |
          git config --global user.name "googifloop"
          git config --global user.email "googifloop424@gmail.com"
          git add version.txt
          git commit -m "chore: update version.txt [skip ci]" || exit 0
          git push